### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by HoangNgo88** [nanopoly/nanopoly-zeromq#24]
Hi, I am reading your project and I love this project
I have a question, why do you choose ZeroMQ in your project instead of others like RabbitMQ or Kafka, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose ZeroMQ instead of others like RabbitMQ or Kafka

**Comment by umuplus** [comment]
Hi, this is an abandoned project unfortunately. The idea was to implement a simple + reusable structure and apply it for various advanced socket libraries. At the time, I started with ZeroMQ and nanomsg. These are actually plugins for https://github.com/nanopoly/nanopoly. The plan was to implement this in other languages I used to work with such as Java and Python. So it's just an opinionated approach.

Ready to use message queues like the ones you mentioned have their own client libraries. Creating a wrapper like these didn't make sense at the time.

Only updates to these repos are from dependency bot actually.
